CREATE TABLE MARKET_MAKER_IDENTIFICATION_MATRIX (
    ACCOUNT_ID                  INT         NOT NULL,
    DATA_FROM_DATE              DATE        NOT NULL,
    SYMBOL                      CHAR(6)     NOT NULL,
    PLACE_CANCEL_TIME_DIFF      NUMERIC,
    BID_ASK_RATIO_MEDIAN        NUMERIC,
    BID_ASK_RATIO_STD           NUMERIC,
    IS_INSTITUTIONAL            BOOLEAN,
    FILL_BUY_ORDERS_COUNT       NUMERIC,
    FILL_SELL_ORDERS_COUNT      NUMERIC,
    FILL_BUY_ORDERS_QUANTITY    NUMERIC,
    FILL_SELL_ORDERS_QUANTITY   NUMERIC,
    TOTAL_ORDERS                INT,
    CANCEL_ORDERS               NUMERIC,
    MAKER_COUNTS                NUMERIC,
    TAKER_COUNTS                NUMERIC,
    MARKET_MAKER                BOOLEAN,
    PRIMARY KEY (ACCOUNT_ID, DATA_FROM_DATE, SYMBOL)
);

CREATE INDEX idx_market_maker_identification_matrix_1 ON MARKET_MAKER_IDENTIFICATION_MATRIX (SYMBOL);
CREATE INDEX idx_market_maker_identification_matrix_2 ON MARKET_MAKER_IDENTIFICATION_MATRIX (DATA_FROM_DATE);